### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by yuki3568** [yuki3568/Animal-Bliss#16]
■Webアプリの概要
短時間で癒されることを目的とした、youtubeに投稿されている動物のショート動画を共有し合えるサービスです。

■1週間辺りの開発に向けられる時間
- 1週間あたり：28時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

■ProjectsのURL
作成したProjects（看板・issue・ストーリーポイントが確認できるもの且つ他者でも閲覧可能状態）のURLを貼り付けてください。

■MVPリリースまで
- [ ] rails new
- [ ] Fly.ioにデプロイ
- [ ] トップページの作成
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] ログアウト機能
- [ ] 新規投稿ページの作成
- [ ] 動画投稿機能
- [ ] 動画削除機能
- [ ] 一覧表示ページの作成
- [ ] 詳細ページの作成
- [ ] 検索機能
- [ ] コメント投稿機能
- [ ] コメント編集機能

■MVP後
- [ ] パスワードリセット機能
- [ ] パスワード更新
- [ ] YouTube APIを使った動画の投稿制限
- [ ] マイページ
- [ ] お気に入り機能
- [ ] タグ機能
- [ ] "癒された！"ボタン機能
- [ ] "癒された！"数による動画のランキング機能
- [ ] "癒された！"数に応じて、ユーザーに称号を与える機能
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ

■MVPレビュー依頼予定日
予定日：2024年 12月 15日

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
以下、コメントになります。

---

- #6 でログイン機能を実装予定かと思いますが、「ログアウト機能」のissueが見当たらなかったのでご確認をお願いします。
- 新規投稿、一覧、詳細などはありますが、「編集」「削除」機能を実装するissueは必要なさそうでしょうか？

**Comment by yuki3568** [comment]
issueの概要を下記の通り変更しましたので、ご確認をお願いたします。

---

・「ログアウト機能」のissueを追加しました。
・投稿した動画の「削除機能」のissueを追加しました。
・投稿したコメントの「編集機能」のissueを追加しました。

**Comment by syuuarsaga** [comment]
LGTMです！

**Comment by rdhdchloe** [comment]
LGTMです！
